kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kim-mysql-rolebinding
  namespace: mysql
subjects:
- kind: Group
  name: dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kim-mysql
  apiGroup: rbac.authorization.k8s.io
