apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: operation
  name: kim-operation
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watchi", "update", "patch", "create"]