kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kim-operation-rolebinding
  namespace: operation
subjects:
- kind: Group
  name: dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kim-operation
  apiGroup: rbac.authorization.k8s.io