apiVersion: v1
kind: Pod
metadata:
  namespace: mysql
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-pod
      image: mysql:5.6
      env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: root
      ports:
        - containerPort: 3306
